### ISSUE TITLE
why minio is set to  4 (0-3)?

### ISSUE THREAD

**Issue by Carlospi99** [CAAPIM/apim-charts#105]
https://github.com/CAAPIM/apim-charts/blob/e49e2f359daf35368267e52cb6df4099953a1e83/charts/druid/templates/minio/minio-statefulset.yaml#L40

I am trying to set a HA per AZ, I have tree zones, while with this confugration It will try to check from 0 - 3, whci becuase I am putting afinity to zones. ( 3 zones) one pod for mino will be pending and the pod running will restarting becuase it can find the pod pending..

now if I put my replicas to 3 on minio. it will create 3 pods as required but will still trying to reach the minio missing. and then the pods start to restart..

**Comment by murthyravi14** [comment]
Please refer: https://docs.min.io/docs/distributed-minio-quickstart-guide.html

```
Distributed MinIO provides protection against multiple node/drive failures and bit rot using erasure code. As the minimum disks required for distributed MinIO is 4 (same as minimum disks required for erasure coding), erasure code automatically kicks in as you launch distributed MinIO.
```

**Comment by pisko1979** [comment]
Hi

Maybe should try with at least 6 nodes as minio have requirements for at least 4 node.
If you distribute minio ec accross zones that shoup work.
