### ISSUE TITLE
Add configuration of ssg.policy to the chart similar to system.properties configuration

### ISSUE THREAD

**Issue by spooki3** [CAAPIM/apim-charts#139]
**Which chart**: Gateway version 2.0.4
The name (and version) of the affected chart.

**Is your feature request related to a problem? Please describe.**
We are unable to edit the /opt/SecureSpan/Gateway/runtime/etc/ssg.policy which is required for us. 
See the following knowledge base article
https://knowledge.broadcom.com/external/article/129740/can-not-get-json-data-from-message-targe.html

**Describe the solution you'd like**
A way to configure the /opt/SecureSpan/Gateway/runtime/etc/ssg.policy

**Describe alternatives you've considered**
I don't see any way unless feature request my other feature request (https://github.com/CAAPIM/apim-charts/issues/138) is implemented  However I think that would be unnecessary if configuration is added to the charts similar as done for the system.properties

**Comment by Gazza7205** [comment]
This should be relatively easy to mount - I'll discuss this with the team and check that this feature is same between appliance/container gateways. You should be able to configure this with the same approach as mentioned in #138 short term.

**Comment by Gazza7205** [comment]
These can be configured in Gateway Chart v3.0.2. See examples [here](https://github.com/Layer7-Community/Utilities/tree/main/gateway-init-container-examples)
