### ISSUE TITLE
Sticky session for Kubernetes

### ISSUE THREAD

**Issue by Carlospi99** [CAAPIM/apim-charts#37]
**Which chart**:
gateway

**Is your feature request related to a problem? Please describe.**
When Using the gateway in  Solution like Kubernetes, we have found the problem that if we have more than one Gateway Policy Manager is not keeping the connection stable as the Load balancer start to jump into the available gateway.

**Describe the solution you'd like**
A sticky session that will keep the gateway connect to the same gateway when Using Policy manager, o any other solution that keep us connected to the Gateway with Policy manager

**Describe alternatives you've considered**
Create a second load balancer or tagging in Kubernetes  

.

**Comment by Gazza7205** [comment]
Hi Carlos,

Thanks for raising this, we should be able to add configuration for sticky sessions in values.yaml.
