### ISSUE TITLE
Portal chart does not work with kubernetes 1.19 due to v1beta1 in templates/ingress/ingress.yaml

### ISSUE THREAD

**Issue by voltumna** [CAAPIM/apim-charts#54]
**Which chart**:
portal

**Describe the bug**
Portal chart does not work with kubernetes 1.19 due to v1beta1 in templates/ingress/ingress.yaml

**To Reproduce**
kind create cluster --name layer7 --image kindest/node:v1.19.1
helm repo add layer7 https://caapim.github.io/apim-charts/
helm repo update
helm install my-portal --set-file "portal.registryCredentials=/home/mau/Downloads/docker-secret.yaml" layer7/portal

W0421 12:01:17.561975  525573 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0421 12:01:17.566282  525573 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Timeout

**Expected behavior**
It should succeed  and I should have all the pods running, but none are pulled

**Version of Helm and Kubernetes**:
kubernetes 1.19.1

- Output of `helm version`:
 
```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-16T18:16:59Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

**Additional context**

**Comment by amoghsa** [comment]
@voltumna, we will be starting this work in next PI first thing. This should be ready for upcoming portal release as well. @APIM-KiranVaddadi - Please add more comments if needed.

**Comment by voltumna** [comment]
Thank you for the update, 
Any timeline? 
Thanks

**Comment by amoghsa** [comment]
@APIM-KiranVaddadi - Can you please check with Wai Yin for timeline?

**Comment by APIM-KiranVaddadi** [comment]
@voltumna We are planning to release new portal helm  charts which support K8S 1.20 by mid June.

**Comment by voltumna** [comment]
Thank you @APIM-KiranVaddadi  for the prompt reply, awesome, cannot wait, looking forward to that :)

**Comment by Gazza7205** [comment]
@voltumna - your server version is 1.19 and your client is 1.21.

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"**v1.21.0**", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-16T18:16:59Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"**v1.19.1**", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
**WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1**
```

As per the warning - the v1beta1 API is unavailable in 1.22 so this shouldn't cause the Chart to fail deployment on a 1.19 cluster (just deployed on v1.20.6-34)
```
W0421 12:01:17.561975 525573 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, **unavailable in v1.22+**; use networking.k8s.io/v1 Ingress
```

Our kubeval tests currently cover to 1.19.0

The Portal Ingress ref will still be updated in a subsequent release - in the meantime could you update your kubectl client/versions and try again? (this could also be related to Kind)

**Comment by voltumna** [comment]
Thank you @Gazza7205 , I will check it out again, and let you know what I find

**Comment by voltumna** [comment]
Hi @Gazza7205 ,
I have downloaded the latest from here, and created a kind cluster version 1.19.0
here is what I get: 
```
helm install my-portal --set-file "portal.registryCredentials=./Downloads/docker-secret.yaml" . --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: ./Documents/Layer7/K8S/apim-charts-stable/charts/portal

W0426 14:52:36.213751  356394 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0426 14:52:36.214584  356394 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
client.go:282: [debug] Starting delete for "broadcom-apim" Secret
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "my-portal-cert-update" Role
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "my-portal-cert-update" RoleBinding
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "portal-external-secret" Secret
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "portal-internal-secret" Secret
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "my-portal" ServiceAccount
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "my-portal-job-secret" Secret
client.go:122: [debug] creating 1 resource(s)
client.go:282: [debug] Starting delete for "my-portal-tls-manager" Job
client.go:311: [debug] jobs.batch "my-portal-tls-manager" not found
client.go:122: [debug] creating 1 resource(s)
client.go:491: [debug] Watching for changes to Job my-portal-tls-manager with timeout of 5m0s
client.go:519: [debug] Add/Modify event for my-portal-tls-manager: ADDED
client.go:558: [debug] my-portal-tls-manager: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:519: [debug] Add/Modify event for my-portal-tls-manager: MODIFIED
client.go:558: [debug] my-portal-tls-manager: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
```

Also, when I look at the logs on lens, I see the following: 

![image](https://user-images.githubusercontent.com/1274922/116088119-db0deb00-a6a1-11eb-9eb1-6d2f370004be.png)

Can you help?

thanks

Maurizio

**Comment by Gazza7205** [comment]
@voltumna - this doesn't look related to the Chart. I would check that your Kind Cluster can resolve and reach docker.io.
